version: "3.7"
services:
  db:
    image: mysql:8.0.19
    command: '--default-authentication-plugin=mysql_native_password'
    # restart: always
    secrets:
      - db-password
    networks: 
      - backend-network
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  app:
    build: app
    # restart: always
    volumes:
      - ./app/src:/code
    networks: 
      - backend-network
      - frontend-network
    secrets:
      - db-password
    ports:
      - 5678:5678

  web:
    build: web
    # restart: always
    ports:
      - 80:80
    networks: 
      - frontend-network

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backend-network:
  frontend-network: